name: Build And Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          echo "Using legacy backup workflow. Consider migrating to the new 'build-and-test.yml' in the root."
      - name: Run tests
        run: echo "Running tests..."
