name: Build And Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          echo "Setting up..."
          rm /workspaces/--ThinkAlike--/.github/workflows/backup/build-and-test.yml
      - name: Run tests
        run: echo "Running tests..."
