name: Build Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install documentation dependencies
        run: pip install mkdocs mkdocs-material pymdown-extensions
      - name: Build Documentation
        run: mkdocs build
