name: Frontend CI
'on':
  push:
    branches:
    - main
    - develop
    paths:
    - frontend/**
    - .github/workflows/frontend.yml
  pull_request:
    branches:
    - main
    - develop
    paths:
    - frontend/**
    - .github/workflows/frontend.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: cd frontend && npm ci
    - name: Run tests
      run: cd frontend && npm test
