name: Placeholder Workflow
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: {}
true:
  workflow_dispatch: null
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder Step
      run: echo "This is a placeholder workflow"
