repos:
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.15.0
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
