repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use a version that exists
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.0  # Use a version that exists
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import,undefined-variable]
        exclude: ^(tests/|examples/|docs/)
