site_name: "ThinkAlike Documentation"
site_description: Documentation for the ThinkAlike project
site_url: https://eoslumina.github.io/--ThinkAlike--/

theme:
  name: material
  palette:
    primary: indigo
    accent: amber
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - redirects:
      redirect_maps:
        "guides/developer_guides/data_handling_policy_guide.md": "guides/developer_guides/data_handling.md"
        "core/contributing.md": "core/contributing/index.md"
        "core/installation.md": "core/setup/installation.md"
        "core/onboarding_guide.md": "core/getting_started/onboarding.md"
        "components/ui_components/data_traceability.md": "components/ui/data_traceability/index.md"
        "core/ethics/ethical_guidelines/ethical_guidelines.md": "core/ethics/ethical_guidelines.md"
        "templates/code_documentation_template.md": "core/templates/code_documentation.md"
        "components/ui_components/CoreValuesValidator.md": "components/ui/core_values_validator.md"
        "components/ui_components/APIValidator.md": "components/ui/api_validator.md"
        "components/ui_components/DataTraceability.md": "components/ui/data_traceability.md"

validation:
  ignore_links:
    - "mailto:*"
    - "http*://*"
  ignore_paths:
    - "templates/*"
    - "README.md"
  absolute_links: warn
  nav: warn
  links: warn

strict: true
docs_dir: "docs"
site_dir: "site"

nav:
  - Home: index.md
  - Core:
      - Enlightenment 2.0 Principles: core/enlightenment_2_0/enlightenment_2_0_principles.md
      - Ethical Guidelines: core/ethics/ethical_guidelines.md
      - Contributing: core/contributing.md
      - Installation: core/installation.md
      - Onboarding Guide: core/onboarding_guide.md
  - Vision:
      - Core Concepts Explained: vision/core_concepts.md
      - Blockchain Integration: vision/blockchain_integration.md
  - Architecture:
      - Architectural Overview: architecture/architectural_overview.md
      - API Endpoints (Mode 2): architecture/api/api_endpoints_mode2.md
  - Development:
      - Code Style Guide: guides/developer_guides/code_style_guide.md
      - Building Backend Endpoint Guide: guides/developer_guides/building_backend_endpoint.md
      - Building UI Component Guide: guides/developer_guides/building_ui_component.md
      - UI Validation Examples: guides/developer_guides/ui_validation_examples.md
      - Git Workflow Standard: guides/developer_guides/git_workflow.md
      - GitHub Actions Workflow Format: guides/development/github_actions_workflow_format.md
  - DevOps:
      - DevOps Workflow Guide: guides/devops/devops_workflow.md
      - CI/CD Workflow Reference: guides/devops/ci_cd_workflow_reference.md
