site_name: "ThinkAlike Documentation"

theme:
  name: material

plugins:
  - search
  - redirects:
      redirect_maps: {}

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

validation:
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home: index.md

docs_dir: "docs"
site_dir: "site"
