name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Clean up legacy workflows
        run: bash scripts/cleanup_workflows.sh

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        node-version: ["18.x"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r requirements-test.txt
      - name: Run Backend Tests
        run: |
          cd backend
          pytest
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python for docs
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install MkDocs, Material Theme, and pymdown-extensions
        run: pip install mkdocs mkdocs-material pymdown-extensions
      - name: Build Documentation
        run: mkdocs build
