name: ThinkAlike Basic CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  # This job has no dependencies - will run first
  verify:
    name: Basic Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint with pylint
        run: |
          # Run pylint on Python files
          find . -type f -name "*.py" | xargs pylint --disable=C0111,C0103,C0303,C0330
        continue-on-error: true  # Don't fail the build for linting issues

      - name: Run tests
        run: |
          pytest --verbose

  # This job depends on the first job
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "Building ThinkAlike components"
          # Add build steps specific to your project here
          
      - name: Create build artifacts
        run: |
          mkdir -p ./artifacts
          echo "Build completed at $(date)" > ./artifacts/build_info.txt
          # Add real artifact creation here
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./artifacts/
          retention-days: 7
