name: Update Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install mkdocs mkdocs-material

      - name: Build Documentation
        run: mkdocs build

      - name: Deploy Documentation
        if: success()
        run: mkdocs gh-deploy
