version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - DATABASE_URL=sqlite:///./app.db
    depends_on:
      - db
    networks:
      - thinkalike-network

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=thinkalike
      - POSTGRES_PASSWORD=thinkalike
      - POSTGRES_DB=thinkalike
    networks:
      - thinkalike-network

networks:
  thinkalike-network:
    driver: bridge

volumes:
  postgres-data:
