# Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-04-20 09:12:00
# Current User's Login: EosLumina

name: Backend CI

on:
  push:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - "backend/pyproject.toml"
  pull_request:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - "backend/pyproject.toml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # --- THIS IS THE STEP TO CHECK CAREFULLY ---
      - name: Install dependencies
        working-directory: ./backend
        # Place the disable comment EXACTLY here, before the 'run:' key
        # actionlint-disable-shellcheck: SC2102
        run: |
          echo "Listing backend directory contents:"
          ls -la
          python -m pip install --upgrade pip
          pip install -e .[test,lint]
      # --- END STEP TO CHECK ---

      - name: Run tests
        working-directory: ./backend
        # Ensure no disable comment is here
        run: |
          pytest tests --cov=.

      - name: Lint with flake8
        working-directory: ./backend
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics


