name: Backend CI

on:
  push:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - "backend/pyproject.toml"
  pull_request:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - "backend/pyproject.toml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Updated action version (was v3)
      - uses: actions/checkout@v4
        with:
          submodules: false # Explicitly disable submodule checkout

      # Updated action version (was v4)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: ./backend
        # actionlint-disable-shellcheck: SC2102
        # The SC2102 warning from shellcheck is likely a false positive
        # triggered by the pip install extras syntax '.[test,lint]'.
        run: |
          echo "Listing backend directory contents:"
          ls -la
          python -m pip install --upgrade pip
          pip install -e .[test,lint]

      - name: Run tests
        working-directory: ./backend
        run: |
          pytest tests --cov=.

      - name: Lint with flake8
        working-directory: ./backend
        run: |
          # Consider adding --exit-zero if you want linting errors to not fail the build
          # Or add --max-complexity, --max-line-length etc.
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

