name: Backend CI
'on':
  push:
    branches:
    - main
    - develop
    paths:
    - backend/**
    - .github/workflows/backend.yml
    - requirements.txt
    - pyproject.toml
  pull_request:
    branches:
    - main
    - develop
    paths:
    - backend/**
    - .github/workflows/backend.yml
    - requirements.txt
    - pyproject.toml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install pytest pytest-cov

        pip install -r requirements.txt'
    - name: Run tests
      run: pytest backend/tests --cov=backend --cov-report=xml
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
