name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "main.py"
      - "requirements.txt"
      - ".github/workflows/backend.yml"
  pull_request:
    branches: [main]
    paths:
      - "app/**"
      - "main.py"
      - "requirements.txt"
      - ".github/workflows/backend.yml"

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
          if [ -f requirements.txt ]; then
            grep -v "^-e .*" requirements.txt | grep -v "^file:.*" > github_requirements.txt
            pip install -r github_requirements.txt
          fi

      - name: Run linters
        run: |
          flake8 app/ main.py
          black --check app/ main.py
          isort --check app/ main.py

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then
            grep -v "^-e .*" requirements.txt | grep -v "^file:.*" > github_requirements.txt
            pip install -r github_requirements.txt
          fi

      - name: Run tests
        run: |
          pytest --cov=app tests/
