name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Or your desired Python version

      - name: Install dependencies (Placeholder)
        run: |
          python -m venv venv
          source venv/bin/activate
          # pip install -r requirements.txt  # Add this line later when requirements.txt exists
          pip install flake8 # Install linter directly for now
          echo "Dependencies installed (placeholder)"

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests (Placeholder)
        run: |
          source venv/bin/activate
          # pytest  # Add this line later when tests exist
          echo "Tests passed (placeholder)"
