# Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-04-20 09:15:00
# Current User's Login: EosLumina

# actionlint-disable-shellcheck: All shellcheck checks disabled for this file due to persistent SC2102 misattribution
name: Backend CI

on:
  push:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - "backend/pyproject.toml"
  pull_request:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - "backend/pyproject.toml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: ./backend
        # Removed the specific disable comment from here
        run: |
          echo "Listing backend directory contents:"
          ls -la
          python -m pip install --upgrade pip
          pip install -e .[test,lint]

      - name: Run tests
        working-directory: ./backend
        run: |
          pytest tests --cov=.

      - name: Lint with flake8
        working-directory: ./backend
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

