name: Backend CI

on:
  push:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - "backend/pyproject.toml"
  pull_request:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - "backend/pyproject.toml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false # Explicitly disable submodule checkout

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          echo "Listing backend directory contents:"
          ls -la  # Add this line to list files
          python -m pip install --upgrade pip
          pip install -e .[test,lint]

      - name: Run tests
        working-directory: ./backend
        run: |
          pytest tests --cov=.

      - name: Lint with flake8
        working-directory: ./backend
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
