---
name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "requirements.txt"
  pull_request:
    branches: [main]
    paths:
      - "**.py"
      - "requirements.txt"

jobs:
  build:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
