name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - '.github/workflows/backend_ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - '.github/workflows/backend_ci.yml'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-cov
      - name: Lint
        run: flake8 .
      - name: Test
        run: pytest --cov=.
      - name: Security scan
        run: pip install bandit && bandit -r .
