name: Build And Test
'on':
  push:
    branches:
    - main
    paths: &id001
    - frontend/**
    - '*.js'
    - '*.ts'
    - '*.jsx'
    - '*.tsx'
  pull_request:
    branches:
    - main
    paths: *id001
  workflow_dispatch: {}
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: echo "Setting up..."
    - name: Run tests
      run: echo "Running tests..."
