name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PYTHON_VERSION: "3.10"
  NODE_VERSION: "18.x"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean files
        run: |
          echo "Removing null bytes from source files..."
          find . -type f -name "*.py" -exec sed -i 's/\x0//g' {} \;
      - name: Verify repository structure
        run: |
          if [ ! -d "backend" ] || [ ! -d "frontend" ]; then
            echo "Error: Required directories not found"
            exit 1
          fi

  test:
    needs: verify
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Install test dependencies first
          pip install -r requirements-test.txt
          # Then install project dependencies
          pip install -r requirements.txt
          pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          cd backend
          python -m pytest -v tests/

  docs:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install doc dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material "pymdown-extensions>=10.0"

      - name: Build docs
        run: mkdocs build --clean --strict

  frontend:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run tests
        working-directory: frontend
        run: npm test -- --passWithNoTests
