name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Verify requirements.txt
        run: |
          if [ ! -f requirements.txt ]; then
            echo "Error: requirements.txt not found."
            exit 1
          fi

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pytest (if not included in requirements.txt)
        run: |
          python -m pip install pytest

      - name: Run Tests
        run: pytest
