---
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # yamllint disable rule:truthy
  workflow_dispatch: {}
  # yamllint enable rule:truthy

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Clean up legacy workflows
        run: |
          if [ -f scripts/cleanup_workflows.sh ]; then
            bash scripts/cleanup_workflows.sh
          else
            echo "Cleanup script not found, skipping."

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        node-version: ["18.x"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Backend
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r requirements-test.txt
      - name: Run Backend Tests
        run: |
          cd backend
          pytest

      # Frontend
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Frontend dependencies
        run: |
          cd frontend
          npm ci
      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python for docs
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install MkDocs, Material Theme, and pymdown-extensions
        run: pip install mkdocs mkdocs-material pymdown-extensions
      - name: Build Documentation
        run: mkdocs build

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            thinkalike/web:${{ github.sha }}
            thinkalike/web:latest
          cache-from: type=registry,ref=thinkalike/web:latest
          cache-to: type=inline

# filepath: .yamllint
extends: default

rules:
  truthy:
    level: disable
