name: ThinkAlike CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use latest major version

      - name: Set up Python
        uses: actions/setup-python@v5 # Use latest major version
        with:
          python-version: '3.10' # Or your project's version
          cache: 'pip'

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort # Add other linters if needed

      - name: Run Python Linters
        run: |
          echo "Running Flake8..."
          # Adjust paths if your code is not in the root or standard locations
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true # Allow failure for now
          echo "Running Black check..."
          black . --check || true # Allow failure for now
          echo "Running isort check..."
          isort . --check-only || true # Allow failure for now

      # Add frontend linting steps if applicable (e.g., ESLint)
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18' # Or your project's version
      #     cache: 'npm'
      # - name: Install Node dependencies
      #   run: npm ci # Assuming package-lock.json exists in the root or frontend/
      # - name: Run ESLint
      #   run: npm run lint # Assuming a lint script exists in package.json

  test-backend:
    name: Test Backend (Python)
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov # Add other test deps
          # Install main dependencies - adjust path if needed
          # Check both root and backend/ for requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
          # Add test-specific requirements if they exist
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi


      - name: Run Python tests with coverage
        run: |
          # Adjust path to tests and source code as needed. Assuming tests are in 'tests/' or 'backend/tests/'
          # and source code is in '.' or 'backend/'
          pytest --cov=. --cov-report=xml --cov-report=term || true # Allow failure for now
        # Optionally upload coverage
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # Optional: Requires Codecov setup
      #     files: ./coverage.xml

  # Add test-frontend job if applicable
  # test-frontend:
  #   name: Test Frontend (JS/TS)
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18'
  #         cache: 'npm'
  #     - name: Install Node dependencies
  #       # Adjust path if package.json is in frontend/
  #       run: |
  #         if [ -f frontend/package.json ]; then cd frontend && npm ci; else npm ci; fi
  #     - name: Run frontend tests
  #       # Adjust path if package.json is in frontend/
  #       run: |
  #         if [ -f frontend/package.json ]; then cd frontend && npm test; else npm test; fi # Assuming a test script exists
