/workspaces/--ThinkAlike--/
├── .github/          # GitHub workflows
├── .vscode/          # VS Code settings
├── backend/          # Backend code
├── config/           # Configuration files
├── docs/            # Documentation
│   ├── guides/      # User guides
│   ├── reports/     # Status reports│   └── core/        # Core documentation├── frontend/        # Frontend code├── scripts/         # Utility scripts└── requirements*    # Python requirements files