name: Consolidated CI

'on':
  push:
    branches:
    - main
    paths:
    - backend/**
    - frontend/**
    - tests/**
    - requirements*.txt
    - pyproject.toml
  pull_request:
    branches:
    - main
    paths:
    - backend/**
    - frontend**
    - tests/**
    - requirements*.txt
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: pytest
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Build application
        working-directory: ./frontend
        run: npm run build
