name: Consolidated CI

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "frontend/**"
      - "tests/**"
      - "requirements*.txt"
      - "pyproject.toml"
      - ".github/workflows/consolidated-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - "frontend/**"
      - "tests/**"
      - "requirements*.txt"
      - "pyproject.toml"
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with debug logging enabled"
        required: false
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: Fix test files
        run: |
          python scripts/fix_tests.py --skip-deps

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 backend tests

      - name: Test with pytest
        run: |
          pytest tests/ --cov=backend --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
