name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -e .

      - name: Run tests
        run: |
          python -m pytest

      - name: Package application
        run: |
          mkdir -p dist
          cp -r backend dist/
          echo "Application packaged for deployment"

      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Add your deployment commands here
