name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use string format with quotes and specify a supported version

      - name: Verify requirements.txt
        run: |
          if [ ! -f requirements.txt ]; then
            echo "Error: requirements.txt not found."
            exit 1
          fi

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pytest (if not included in requirements.txt)
        run: |
          python -m pip install pytest

      - name: Run Tests
        run: pytest

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # Add deployment commands here
          # Example: rsync, scp, or cloud deployment commands
