name: Documentation Sovereignty

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'scripts/sovereignty/**'
      - '.github/workflows/doc_sovereignty.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'scripts/sovereignty/**'

jobs:
  verify-integrity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Verify documentation sovereignty
        run: |
          python backend/tools/documentation_cli.py verify
