name: Documentation CI

on:
  push:
    paths:
      - 'docs/**'
      - '**.md'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'docs/**'
      - '**.md'
    branches: [ main, develop ]

jobs:
  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint "**/*.md" --ignore node_modules

  check-links:
    name: Check Markdown Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      - name: Check links in Markdown files
        run: |
          find . -name "*.md" | xargs -n1 markdown-link-check -q

  build-docs-site:
    name: Build Documentation Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./docs-site

      - name: Build documentation site
        run: npm run build
        working-directory: ./docs-site

      - name: Upload documentation site artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs-site-build
          path: docs-site/build

  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate Docs
        run: npm run docs
