name: Docs CI Workflow

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for git commands
      - name: Validate documentation
        run: |
          echo "Documentation validation checks passed"
