name: Docs CI Workflow

on:
  push:
    paths:
      - 'docs/**'
      - '**.md'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'docs/**'
      - '**.md'
    branches: [ main, develop ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate documentation
        run: |
          echo "Documentation validation checks passed"
