name: Documentation Validation

on:
  push:
    branches: [main, develop]
    paths:
      - "docs/**"
      - "**.md"
  pull_request:
    branches: [main, develop]
    paths:
      - "docs/**"
      - "**.md"

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      # Updated action version
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false # Explicitly disable submodule checkout
      - name: Validate markdown
        run: |
          echo "Running markdown validation"
          # Add actual validation command here
          # Example using markdownlint-cli:
          # npm install -g markdownlint-cli
          # markdownlint "**/*.md" --ignore node_modules
