name: Documentation Validation

on:
  push:
    branches: [ main, develop, docs ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs-validation.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs-validation.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML markdown

      - name: Validate documentation structure
        run: |
          echo "Checking documentation structure..."
          python -c "
          import os
          required_dirs = ['core', 'architecture', 'components', 'guides']
          docs_path = 'docs'
          missing = [d for d in required_dirs if not os.path.isdir(os.path.join(docs_path, d))]
          if missing:
              print(f'Warning: Missing expected documentation directories: {missing}')
          else:
              print('Documentation structure looks good!')
          "
