name: Documentation CI

on:
  push:
    paths:
      - 'docs/**'
      - '**.md'
    branches: [ main ]
  pull_request:
    paths:
      - 'docs/**'
      - '**.md'
    branches: [ main ]

jobs:
  markdown_lint:
    name: Markdown Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint "**/*.md" --ignore node_modules

<<<<<<< HEAD
    - name: Fix common issues
      run: |
        python backend/fix_project.py

    - name: Delete unused branches
      run: |
        git fetch --prune
        for branch in $(git branch -r | grep -v '\->' | grep -v 'main' | grep -v 'master'); do
          git branch -d $branch
        done

    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      if: success() && github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
=======
  build_docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    needs: markdown_lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material

      - name: Build docs
        run: mkdocs build
>>>>>>> 24bdfa5 (Refactor CI/CD workflows: update dependencies, remove redundancies, and add verifications)
