name: Documentation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install mkdocs mkdocs-material

      - name: Build Documentation
        run: mkdocs build

      - name: Validate Documentation
        if: success()
        run: echo "Documentation validation complete"
