name: Documentation CI

on:
  push:
    branches: [main, develop]
    paths:
      - "docs/**"
      - "**.md"
      - "docs/mkdocs.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "docs/**"
      - "**.md"
      - "docs/mkdocs.yml"
  workflow_dispatch: {}

jobs:
  markdown_lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false # Explicitly disable submodule checkout

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Create markdownlint config
        run: |
          echo '{
            "default": true,
            "MD013": false,
            "MD024": false,
            "MD033": false,
            "MD041": false
          }' > .markdownlint.json

      - name: Run markdownlint
        run: markdownlint "**/*.md" --ignore node_modules

  build_docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    needs: markdown_lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false # Explicitly disable submodule checkout

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          pip install markdown jinja2

      - name: Build docs
        working-directory: ./docs
        run: mkdocs build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs-build
          path: ./docs/site
