name: Docs CI

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/docs_ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/docs_ci.yml'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
      - name: Build docs
        run: mkdocs build
      - name: Check links
        run: |
          pip install mkdocs-link-check
          mkdocs build --strict
