name: Documentation

'on':
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'
  workflow_dispatch: {}

jobs:
  markdown_lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install markdownlint
      run: npm install -g markdownlint-cli
    - name: Create markdownlint config
      run: "echo '{\n  \"default\": true,\n  \"MD013\": false,\n  \"MD024\": false,\n\
        \  \"MD033\": false,\n  \"MD041\": false\n}' > .markdownlint.json\n"
    - name: Run markdownlint
      run: markdownlint "**/*.md" --ignore node_modules
    - name: Fix common issues
      run: 'npm install -g markdownlint-cli2

        npx markdownlint-cli2-fix "**/*.md" --ignore node_modules

        '
  build_docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    needs: markdown_lint
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install mkdocs mkdocs-material

        pip install -e .  # Install local package in development mode

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        '
    - name: Build docs
      run: mkdocs build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docs-build
        path: ./site
  deploy_docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build_docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: docs-build
        path: ./site
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
  update_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install mkdocs mkdocs-material

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        '
    - name: Build docs
      run: mkdocs build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
