name: Documentation

'on':
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: Build docs
        run: |
          if [ -f mkdocs.yml ]; then
            mkdocs build
          else
            echo "No mkdocs.yml found, creating minimal configuration"
            echo "site_name: ThinkAlike Documentation" > mkdocs.yml
            echo "docs_dir: docs" >> mkdocs.yml
            mkdocs build
          fi
      - name: Check documentation build output
        run: |
          if [ -d "site" ]; then
            echo "✅ Documentation built successfully"
            find site -type f | wc -l
          else
            echo "❌ Documentation build failed"
            exit 1
          fi
