name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install missing Babel plugin
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object
      
      - name: Create .npmrc for legacy dependencies
        run: echo "legacy-peer-deps=true" > .npmrc
      
      - name: Run tests
        run: npm test -- --passWithNoTests
        env:
          CI: true
