---
name: Frontend CI Checks

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'package.json'
      - '.github/workflows/frontend_ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'package.json'
      - '.github/workflows/frontend_ci.yml'

jobs:
  lint-test-build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Lint frontend code
        working-directory: ./frontend
        run: npm run lint

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --coverage

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
