name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'package.json'
      - '.github/workflows/frontend_ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'package.json'
      - '.github/workflows/frontend_ci.yml'

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test -- --coverage
      - name: Build
        run: npm run build
