name: Lint GitHub Workflows
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: {}
true:
  push:
    branches:
    - main
    paths:
    - .github/workflows/**
  pull_request:
    paths:
    - .github/workflows/**
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download actionlint
      run: "curl -sL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash\
        \ | bash\n# Make actionlint executable\nchmod +x ./actionlint\n\n# Add to\
        \ PATH only in GitHub Actions environment\nif [ -n \"$GITHUB_PATH\" ]; then\n\
        \  echo \"$PWD\" >> $GITHUB_PATH\nelse\n  export PATH=\"$PWD:$PATH\"\nfi\n"
    - name: Run actionlint
      run: 'actionlint -color

        '
