name: Lint GitHub Workflows

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download actionlint
        run: |
          curl -sL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
          # Make actionlint executable
          chmod +x ./actionlint
          
          # Add to PATH only in GitHub Actions environment
          if [ -n "$GITHUB_PATH" ]; then
            echo "$PWD" >> $GITHUB_PATH
          else
            export PATH="$PWD:$PATH"
          fi
      
      - name: Run actionlint
        run: |
          actionlint -color
