name: Docs Lint

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/docs-lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/docs-lint.yml"

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: docs/**/*.md
