name: Run Tests
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: {}
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: "python -m pip install --upgrade pip\nif [ -f requirements-test.txt ];\
        \ then\n  pip install -r requirements-test.txt\nelse\n  pip install httpx\
        \ pandas pytest pytest-cov\nfi\nif [ -f requirements.txt ]; then\n  pip install\
        \ -r requirements.txt\nfi\n"
    - name: Fix corrupted files
      run: python .github/scripts/fix_corrupted_files.py
    - name: Run tests
      run: pytest
    - name: Check for test files
      run: "files=$(find . -name \"test_*.py\")\nif [ -z \"$files\" ]; then\n  echo\
        \ \"No test files found!\"\n  exit 1\nfi\necho \"Found test files: $files\"\
        \n"
    - name: Verify test files
      run: python .github/scripts/verify_test_files.py "$(find . -name "test_*.py")"
