name: Repository Settings

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Apply settings
        run: echo "Applying repository settings"
