# Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): 2025-04-20 09:22:00
# Current User's Login: EosLumina

name: Update Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "backend/app/models/**"
      - "backend/app/api/**"

jobs:
  update-api-docs:
    runs-on: ubuntu-latest
    steps:
      # Updated action version (was v3)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false # Explicitly disable submodule checkout

      # Updated action version (was v4)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Update API documentation
        run: |
          python -m pip install --upgrade pip
          # Assuming requirements.txt exists at the root or correct path
          pip install -r requirements.txt
          python backend/tools/documentation_cli.py generate-summary
